In [36]:
import numpy as np
arr=np.arange(0,100,5)
print(arr)
print(arr[1])

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
5


In [37]:
a=np.arange(0, 10)
b=a.copy()
b[3]=10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 10  4  5  6  7  8  9]


In [38]:
np_array= np.array([1,2,3,4,5,6,7,8,9])
print(type(np_array))

<class 'numpy.ndarray'>


In [39]:
a=np.arange(1, 10)
exp=a[::-2]
print(exp)

[9 7 5 3 1]


In [40]:
b=np.arange(1, 100, 3)
print(b)




[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]


In [41]:
c=np.zeros(10)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [42]:
d=np.ones(10)
print(d)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [43]:
np_array=np.arange(50)
result=np_array.reshape(5, 10)
print(result)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [44]:
numbers= np.arange(0, 100)
print(numbers)
result= numbers+10
print(result)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100 101 102 103 104 105 106 107 108 109]


In [45]:
num=np.arange(1,20)
result=np.log(num)
print(result)

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665
 2.56494936 2.63905733 2.7080502  2.77258872 2.83321334 2.89037176
 2.94443898]


In [46]:
num1=np.array([[1,2,3],[4,5,6]])
num2=np.array([[10,20,30],[40,50,60]])
result=np.hstack((num1,num2))
print(result)

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


In [47]:
result= num1 >=2
print(result)

[[False  True  True]
 [ True  True  True]]


In [48]:
result= num2 %6
print(result)

[[4 2 0]
 [4 2 0]]


In [49]:
b=np.array([[0,3,4],[6,12,56],[78,0,4]])
exp=b[:,0:2]
print(exp)

[[ 0  3]
 [ 6 12]
 [78  0]]


In [50]:
dizi=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(dizi[2,1])

8


In [51]:
arr1=np.arange(20)
shape=arr1.reshape(5,4)
print(shape)
print(shape.sum(axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[40 45 50 55]


In [52]:
rand_num=np.random.randint(0,10,10)
result=rand_num.max()
print(rand_num)
print(result)

[5 4 5 5 9 1 8 5 8 2]
9


In [53]:
result5=np.random.randn(5)
print(result5)

[ 0.90349799  0.16077488  0.4610534   0.85616321 -0.80228198]


In [54]:
a=np.arange(1, 10)
exp=a[:]
print(exp)

[1 2 3 4 5 6 7 8 9]


In [63]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [57]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
np.random.randint(5)

0

In [65]:
np.random.randn(5)

array([ 0.19414509, -0.50283838,  1.60553953, -1.53006595,  0.6670703 ])